name: Continuous Delivery
on:
  push:
    branches:
      - main # qualquer outro branch que você queira monitorar

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
            name: projetozipado.zip
            path: |
                "**.py"
                Readme.md
